---

- name: Deploy ec2 instance
  ec2:
    region: eu-west-2
    key_name: ansible-master@aws
    instance_type: t2.micro
    image: ami-403e2524
    wait: true
    exact_count: 1
    vpc_subnet_id: subnet-13011668
    assign_public_ip: true
    instance_tags:
      Name: elk-server
      Role: Testing
      Creator: Carlos Francia
      Tool: Ansible
    count_tag:
      Name: elk-server
  register: ec2

- name: debug Hostvars
  debug:
    var: hostvars

- name: debug ec2
  debug:
    var: ec2.tagged_instances

- name: Add instances to elk server group
  add_host:
    hostname: "{{ item.public_ip }}"
    groupname: elk-server
  with_items: "{{ ec2.tagged_instances }}"

- name: debug Hostvars2
  debug:
    var: hostvars

- name: Wait dor ec2 instance to come online
  wait_for:
    port: 22
    host: "{{ item.public_dns_name }}"
    delay: 60
    timeout: 320
    state: started
  with_items: "{{ ec2.tagged_instances }}"

