---

- name: Install Docker CE and dependencies
  yum:
    name: "{{ item  }}"
    state: present
  with_items: "{{ packages_preparation }}"

- name: Install pip docker library
  pip:
    name: docker
    version: 3.1.4 

- name: Install pip docker-compose library
  pip:
    name: docker-compose
    version: 1.20.1

- name: Install pip dependencies
  pip:
    name: "{{ item }}"
  with_items: "{{ pip_dependencies }}"
